### ISSUE TITLE
Not working in Arch Linux 4.8.13-1-ARCH, GNOME

### ISSUE THREAD

**Issue by alaneuler** [Acolarh/colorgrab#5]
![screenshot from 2017-01-23 19-33-55](https://cloud.githubusercontent.com/assets/8054939/22202409/04781d12-e1a3-11e6-8d55-b9d004335810.png)
and the backtrace is:
[backtrace.txt](https://github.com/nielssp/colorgrab/files/723421/backtrace.txt)

**Comment by nielssp** [comment]
I've been able to replicate the issue in GNOME on Wayland (works fine in X). Unfortunately I don't think there's much I can do about it, since I can't seem to find any color picker that actually works in Wayland.
From this article: https://lwn.net/Articles/607091/ it sound like Wayland prevents applications from getting any pixel information from the screen (for security reasons). As far as I can tell, this pretty much prevents any attempt at implementing a color picker in Wayland.

**Comment by alaneuler** [comment]
OK, thanks! Maybe I should turn to X from Wayland.
